// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robin_log_record.proto

package robin.protobuf;

public final class RonbinLoggerProto {
  private RonbinLoggerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RonbinRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:robin.protobuf.RonbinRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int64 version = 1;</code>
     */
    long getVersion();

    /**
     * <code>required .robin.protobuf.RobinRequest request = 2;</code>
     */
    boolean hasRequest();
    /**
     * <code>required .robin.protobuf.RobinRequest request = 2;</code>
     */
    robin.protobuf.RobinRequestProto.RobinRequest getRequest();
    /**
     * <code>required .robin.protobuf.RobinRequest request = 2;</code>
     */
    robin.protobuf.RobinRequestProto.RobinRequestOrBuilder getRequestOrBuilder();
  }
  /**
   * Protobuf type {@code robin.protobuf.RonbinRecord}
   */
  public  static final class RonbinRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:robin.protobuf.RonbinRecord)
      RonbinRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RonbinRecord.newBuilder() to construct.
    private RonbinRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RonbinRecord() {
      version_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RonbinRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt64();
              break;
            }
            case 18: {
              robin.protobuf.RobinRequestProto.RobinRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(robin.protobuf.RobinRequestProto.RobinRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return robin.protobuf.RonbinLoggerProto.internal_static_robin_protobuf_RonbinRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return robin.protobuf.RonbinLoggerProto.internal_static_robin_protobuf_RonbinRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              robin.protobuf.RonbinLoggerProto.RonbinRecord.class, robin.protobuf.RonbinLoggerProto.RonbinRecord.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_;
    /**
     * <code>required int64 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 version = 1;</code>
     */
    public long getVersion() {
      return version_;
    }

    public static final int REQUEST_FIELD_NUMBER = 2;
    private robin.protobuf.RobinRequestProto.RobinRequest request_;
    /**
     * <code>required .robin.protobuf.RobinRequest request = 2;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .robin.protobuf.RobinRequest request = 2;</code>
     */
    public robin.protobuf.RobinRequestProto.RobinRequest getRequest() {
      return request_ == null ? robin.protobuf.RobinRequestProto.RobinRequest.getDefaultInstance() : request_;
    }
    /**
     * <code>required .robin.protobuf.RobinRequest request = 2;</code>
     */
    public robin.protobuf.RobinRequestProto.RobinRequestOrBuilder getRequestOrBuilder() {
      return request_ == null ? robin.protobuf.RobinRequestProto.RobinRequest.getDefaultInstance() : request_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getRequest().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getRequest());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRequest());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof robin.protobuf.RonbinLoggerProto.RonbinRecord)) {
        return super.equals(obj);
      }
      robin.protobuf.RonbinLoggerProto.RonbinRecord other = (robin.protobuf.RonbinLoggerProto.RonbinRecord) obj;

      boolean result = true;
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && (getVersion()
            == other.getVersion());
      }
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getVersion());
      }
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static robin.protobuf.RonbinLoggerProto.RonbinRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static robin.protobuf.RonbinLoggerProto.RonbinRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static robin.protobuf.RonbinLoggerProto.RonbinRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static robin.protobuf.RonbinLoggerProto.RonbinRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static robin.protobuf.RonbinLoggerProto.RonbinRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static robin.protobuf.RonbinLoggerProto.RonbinRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static robin.protobuf.RonbinLoggerProto.RonbinRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static robin.protobuf.RonbinLoggerProto.RonbinRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static robin.protobuf.RonbinLoggerProto.RonbinRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static robin.protobuf.RonbinLoggerProto.RonbinRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static robin.protobuf.RonbinLoggerProto.RonbinRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static robin.protobuf.RonbinLoggerProto.RonbinRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(robin.protobuf.RonbinLoggerProto.RonbinRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code robin.protobuf.RonbinRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:robin.protobuf.RonbinRecord)
        robin.protobuf.RonbinLoggerProto.RonbinRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return robin.protobuf.RonbinLoggerProto.internal_static_robin_protobuf_RonbinRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return robin.protobuf.RonbinLoggerProto.internal_static_robin_protobuf_RonbinRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                robin.protobuf.RonbinLoggerProto.RonbinRecord.class, robin.protobuf.RonbinLoggerProto.RonbinRecord.Builder.class);
      }

      // Construct using robin.protobuf.RonbinLoggerProto.RonbinRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return robin.protobuf.RonbinLoggerProto.internal_static_robin_protobuf_RonbinRecord_descriptor;
      }

      @java.lang.Override
      public robin.protobuf.RonbinLoggerProto.RonbinRecord getDefaultInstanceForType() {
        return robin.protobuf.RonbinLoggerProto.RonbinRecord.getDefaultInstance();
      }

      @java.lang.Override
      public robin.protobuf.RonbinLoggerProto.RonbinRecord build() {
        robin.protobuf.RonbinLoggerProto.RonbinRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public robin.protobuf.RonbinLoggerProto.RonbinRecord buildPartial() {
        robin.protobuf.RonbinLoggerProto.RonbinRecord result = new robin.protobuf.RonbinLoggerProto.RonbinRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof robin.protobuf.RonbinLoggerProto.RonbinRecord) {
          return mergeFrom((robin.protobuf.RonbinLoggerProto.RonbinRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(robin.protobuf.RonbinLoggerProto.RonbinRecord other) {
        if (other == robin.protobuf.RonbinLoggerProto.RonbinRecord.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        if (!hasRequest()) {
          return false;
        }
        if (!getRequest().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        robin.protobuf.RonbinLoggerProto.RonbinRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (robin.protobuf.RonbinLoggerProto.RonbinRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long version_ ;
      /**
       * <code>required int64 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 version = 1;</code>
       */
      public long getVersion() {
        return version_;
      }
      /**
       * <code>required int64 version = 1;</code>
       */
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0L;
        onChanged();
        return this;
      }

      private robin.protobuf.RobinRequestProto.RobinRequest request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          robin.protobuf.RobinRequestProto.RobinRequest, robin.protobuf.RobinRequestProto.RobinRequest.Builder, robin.protobuf.RobinRequestProto.RobinRequestOrBuilder> requestBuilder_;
      /**
       * <code>required .robin.protobuf.RobinRequest request = 2;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .robin.protobuf.RobinRequest request = 2;</code>
       */
      public robin.protobuf.RobinRequestProto.RobinRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? robin.protobuf.RobinRequestProto.RobinRequest.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>required .robin.protobuf.RobinRequest request = 2;</code>
       */
      public Builder setRequest(robin.protobuf.RobinRequestProto.RobinRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .robin.protobuf.RobinRequest request = 2;</code>
       */
      public Builder setRequest(
          robin.protobuf.RobinRequestProto.RobinRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .robin.protobuf.RobinRequest request = 2;</code>
       */
      public Builder mergeRequest(robin.protobuf.RobinRequestProto.RobinRequest value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              request_ != null &&
              request_ != robin.protobuf.RobinRequestProto.RobinRequest.getDefaultInstance()) {
            request_ =
              robin.protobuf.RobinRequestProto.RobinRequest.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .robin.protobuf.RobinRequest request = 2;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .robin.protobuf.RobinRequest request = 2;</code>
       */
      public robin.protobuf.RobinRequestProto.RobinRequest.Builder getRequestBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>required .robin.protobuf.RobinRequest request = 2;</code>
       */
      public robin.protobuf.RobinRequestProto.RobinRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              robin.protobuf.RobinRequestProto.RobinRequest.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>required .robin.protobuf.RobinRequest request = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          robin.protobuf.RobinRequestProto.RobinRequest, robin.protobuf.RobinRequestProto.RobinRequest.Builder, robin.protobuf.RobinRequestProto.RobinRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              robin.protobuf.RobinRequestProto.RobinRequest, robin.protobuf.RobinRequestProto.RobinRequest.Builder, robin.protobuf.RobinRequestProto.RobinRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:robin.protobuf.RonbinRecord)
    }

    // @@protoc_insertion_point(class_scope:robin.protobuf.RonbinRecord)
    private static final robin.protobuf.RonbinLoggerProto.RonbinRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new robin.protobuf.RonbinLoggerProto.RonbinRecord();
    }

    public static robin.protobuf.RonbinLoggerProto.RonbinRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RonbinRecord>
        PARSER = new com.google.protobuf.AbstractParser<RonbinRecord>() {
      @java.lang.Override
      public RonbinRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RonbinRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RonbinRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RonbinRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public robin.protobuf.RonbinLoggerProto.RonbinRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robin_protobuf_RonbinRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_robin_protobuf_RonbinRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026robin_log_record.proto\022\016robin.protobuf" +
      "\032\023robin_req_res.proto\"N\n\014RonbinRecord\022\017\n" +
      "\007version\030\001 \002(\003\022-\n\007request\030\002 \002(\0132\034.robin." +
      "protobuf.RobinRequestB#\n\016robin.protobufB" +
      "\021RonbinLoggerProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          robin.protobuf.RobinRequestProto.getDescriptor(),
        }, assigner);
    internal_static_robin_protobuf_RonbinRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_robin_protobuf_RonbinRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_robin_protobuf_RonbinRecord_descriptor,
        new java.lang.String[] { "Version", "Request", });
    robin.protobuf.RobinRequestProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
