spring:
  main:
    banner-mode: "off"

robin:
  port: 5010
  binlog:
    file: 'G:\Google Drive\workspace\binlog\data.data'
#   如果是master则配置master数据
  master:
    backup:
      port: 5011
